### ISSUE TITLE
Rails 5?

### ISSUE THREAD

**Issue by Amnesthesia** [russellquinn/casein#75]
Will (or does?) Casein support rails 5?

**Comment by russellquinn** [comment]
I actually haven't tried it on the the Rails 5 beta. Have you?

**Comment by dwaynemac** [comment]
rake tasks are not detected and several warnings appear.

**Comment by russellquinn** [comment]
@dwaynemac Do you want to try and fix it? I won't have time in the coming weeks.

**Comment by simzen85** [comment]
With Rails 5 (beta3), I had this error with an existing Casein generated page

uninitialized constant Casein::CaseinController

Anybody knows how to fix this ?

**Comment by rmanoka** [comment]
The rake failures seem to be because of the version of will_paginate.  To make it work

1.  Clone the git repository
2.  Change lib/casein.rb to support Rails::VERSION::MAJOR >= 4
3.  Change casein.gemspec to gem 'will_paginate', '~> 3.1.0'   (not sure if this optimal as gem build complains)

This version works with rails version Rails 5.0.0.rc1.

**Comment by brchristian** [comment]
Looks like doing the things @rmanoka suggests fixes the problems related to `will_paginate`. However, Casein also depends on `authlogic` which is also currently broken in Rails 5: https://github.com/binarylogic/authlogic/pull/494.

**Comment by brchristian** [comment]
@rmanoka @russellquinn Just an update to this thread, noting that authlogic 3.5.0 has been released, which is Rails 5-compatible. This should be the last hurdle in being able to make Casein Rails 5-compatible as well.

**Comment by weatheredwatcher** [comment]
Followed all the steps above.  Updated casein.rb to ```>= 4```  
Using both updated will_paginate and authlogic 3.5.0.
When I run
```rails g casein:install```
It hangs indefinitely.  On ```ctl-c``` I get the following output:

```
Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/run.rb:117:in `gets': Interrupt                                 │Compressing objects: 100% (4/4), done.
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/run.rb:117:in `verify_server_version'                       'Writing objects: 100% (4/4), 387 bytes | 0 bytes/s, done.
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/run.rb:62:in `run'                                          │Total 4 (delta 3), reused 0 (delta 0)
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/run.rb:42:in `warm_run'                                     │remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/run.rb:35:in `call'                                         │To github.com:weatheredwatcher/oversearch.git
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'                                      │ * [new branch]      development -> development
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/rails.rb:24:in `call'                                       │ weatheredwatcher@weatheredwatcher  ~/source/ruby/oversearch   development 
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'                                      │
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'                                              │
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'                                           │
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'                                            '
 from /Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'                                │
 from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                            │
 from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                            │
 from /Users/weatheredwatcher/source/ruby/weatheredwatcher_com/bin/spring:14:in `<top (required)>'                                                 │
 from bin/rails:3:in `load'                                                                                                                        │
 from bin/rails:3:in `<main>'
```

Then if I try any other task, I get errors, as if it's not fully installing anything.

```rake casein:users:create_admin email=davidduggins@me.com password="password" --trace```

Gets me:

```                                                                                                                                   
** Invoke casein:users:create_admin (first_time)                                                                                                   │
** Invoke environment (first_time)                                                                                                                 │
** Execute environment                                                                                                                             ├───────────────────────────────────────────────────────────────────────────────────────
** Execute casein:users:create_admin                                                                                                               │Started GET "/" for ::1 at 2016-11-12 18:54:22 -0500
rake aborted!                                                                                                                                      'Processing by WelcomeController#index as HTML
NameError: uninitialized constant Casein::ConfigHelper                                                                                             │  Rendering welcome/index.html.erb within layouts/application
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/casein-5.1.1.5/app/models/casein/admin_user.rb:1:in `<top (required)>'                           │  Rendered welcome/index.html.erb within layouts/application (11.0ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'      │Completed 200 OK in 143ms (Views: 133.0ms | ActiveRecord: 0.0ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'            │
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'               │
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/casein-5.1.1.5/lib/railties/tasks.rake:13:in `block (3 levels) in <top (required)>'              │Started GET "/" for ::1 at 2016-11-12 18:54:26 -0500
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'                                           'Processing by WelcomeController#index as HTML
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'                                                       │  Rendering welcome/index.html.erb within layouts/application
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'                                                    │  Rendered welcome/index.html.erb within layouts/application (0.5ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'                            │Completed 200 OK in 66ms (Views: 63.8ms | ActiveRecord: 0.0ms)
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'                                                                  │
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'                                     │
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'                                                     │Started GET "/welcome/index" for ::1 at 2016-11-12 23:48:03 -0500
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'                                         'Processing by WelcomeController#index as HTML
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'                       │  Rendering welcome/index.html.erb within layouts/application
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'                                                │  Rendered welcome/index.html.erb within layouts/application (24.7ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'                                  │Completed 200 OK in 543ms (Views: 481.5ms | ActiveRecord: 0.0ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'                                    '
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'                                           │
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'                                         │Started GET "/" for ::1 at 2016-11-13 00:47:36 -0500
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'                         │Processing by WelcomeController#index as HTML
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'                                                  │  Rendering welcome/index.html.erb within layouts/application
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'                                                    │  Rendered welcome/index.html.erb within layouts/application (63.0ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/bin/rake:23:in `load'                                                                                 'Completed 200 OK in 671ms (Views: 657.5ms | ActiveRecord: 0.0ms)
/Users/weatheredwatcher/.rvm/gems/ruby-2.3.0/bin/rake:23:in `<main>'                                                                               │
Tasks: TOP => casein:users:create_admin
```

Any suggestions on how to fix this would be greatly appreciated.  I've got the time to work on this over the next few days!

**Comment by brchristian** [comment]
@rmanoka @weatheredwatcher I’ve got a rough working branch here at [`rails5`](https://github.com/russellquinn/casein/tree/rails5). Can you have a look and see how this works for you? We should be close to a merge to `master` with a few additional tweaks.

**Comment by weatheredwatcher** [comment]
I tried this out.  I was able to install casein and migrate the db, however the rake tasks and routes are not setting up.

I am using ruby 2.3.1p112 (2016-04-26 revision 54768) and rails 5.0.0.1

/d

**Comment by brchristian** [comment]
@weatheredwatcher I was able to create a new rails 5.0.1 app from scratch using:

```ruby
gem 'casein', git: 'https://github.com/russellquinn/casein.git', branch: 'rails5’
```

and I was able to run the rake tasks and routes okay. Can you give me some details on your setup?

**Comment by brchristian** [comment]
@Amnesthesia @dwaynemac @simzen85 Just a heads up that we have a working `rails5` branch that you’re welcome to try out. If everything checks out, we’ll be merging it into `master` and then hopefully doing a rubygems point release.

**Comment by Amnesthesia** [comment]
Fantastic! Thank you! <3

**Comment by brchristian** [comment]
The `rails5` branch has been working without any new reported issues for two weeks now, so I have merged it into `master`. A gem release will be forthcoming, so I’m closing this issue. If there are any problems, don’t hesitate to open new issues and we will get things sorted out straightaway!

**Comment by michaelachrisco** [comment]
Im getting the same issue as @weatheredwatcher trying out this package with a fresh install of rails:

when I try `casein:install` spring locks up.
```
rails g casein:install
^C/home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/run.rb:117:in `gets': Interrupt
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/run.rb:117:in `verify_server_version'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/run.rb:62:in `run'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/run.rb:42:in `warm_run'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/run.rb:35:in `call'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/rails.rb:24:in `call'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
	from /home/michaelachrisco/.rvm/gems/ruby-2.3.3/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/michaelachrisco/rails5-stupidedi/bin/spring:14:in `require'
	from /home/michaelachrisco/rails5-stupidedi/bin/spring:14:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

I am using casein 5.2.0 with a new install of rails 5.0.1

**Comment by russellquinn** [comment]
@michaelachrisco Can you try a non-Casein generator method to see if that works? e.g.

rails generate controller Greetings hello

**Comment by michaelachrisco** [comment]
Well I feel silly! I could not use any of the generators for some reason on the repo.
It came down to binstubs:

`bundle install --binstubs`
fixed the issue. 

Also running on a new system without the old version of the gem also fixed the issue.

Thanks!

**Comment by russellquinn** [comment]
You're welcome. Good luck!

**Comment by dbachinin** [comment]
I have it issue:

@links=Link.order(sort_order(:given_url)).paginate page: params[:page]
NameError: uninitialized constant Casein::LinksController::Link
	from /home/tg-it-03/src/test/MyPortfolio/app/controllers/casein/links_controller.rb:11:in `index'

When i open link to generated scaffold page, it don`t open.
How to show Casein, where the controller is?
